import SwiftUI

struct LegalView: View {
    let type: LegalType
    
    enum LegalType {
        case terms
        case privacy
        case disclaimer
        
        var title: String {
            switch self {
            case .terms: return "Terms of Service"
            case .privacy: return "Privacy Policy"
            case .disclaimer: return "Investment Disclaimer"
            }
        }
        
        var content: String {
            switch self {
            case .terms: return termsContent
            case .privacy: return privacyContent
            case .disclaimer: return disclaimerContent
            }
        }
    }
    
    var body: some View {
        ZStack {
            AppColors.background.ignoresSafeArea()
            
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    Text(type.title)
                        .font(.custom(AppFonts.serifTitle, size: 32))
                        .fontWeight(.semibold)
                        .foregroundColor(AppColors.text)
                    
                    Text("Last Updated: \(Date().formatted(date: .long, time: .omitted))")
                        .font(.system(size: 13))
                        .foregroundColor(AppColors.textSecondary)
                    
                    Text(type.content)
                        .font(.system(size: 15))
                        .foregroundColor(AppColors.text)
                        .lineSpacing(6)
                }
                .padding(24)
            }
        }
    }
}

// MARK: - Legal Content

private let disclaimerContent = """
INVESTMENT DISCLAIMER

Ticker provides educational information only. This is not financial advice, investment advice, trading advice, or any other sort of advice. You should not treat any of Ticker's content as such.

IMPORTANT NOTICES:

1. Not Financial Advice
Ticker does not recommend that any particular stock, security, portfolio, transaction, or investment strategy is suitable for any specific person. All information provided by Ticker is for educational purposes only.

2. Do Your Own Research
You must always do your own research and due diligence before making any investment decision. You should consult with a licensed financial advisor before making any investment decisions.

3. No Guarantees
Past performance does not guarantee future results. All investments carry risk of loss. You could lose some or all of your investment.

4. Price Information
Stock prices and financial data shown in Ticker are estimates for educational purposes only and may not reflect real-time market prices. Always verify current prices with your broker before making investment decisions.

5. AI-Generated Content
Investment recommendations are generated by artificial intelligence and should be considered as starting points for your own research, not as definitive investment advice.

6. Third-Party Links
Ticker may contain links to third-party brokers and financial services. We are not responsible for the accuracy, legality, or content of external sites. Use of third-party services is subject to their own terms and conditions.

7. No Broker Relationship
Ticker is not a broker-dealer, investment advisor, or financial institution. We do not hold, custody, or manage user funds or investments.

By using Ticker, you acknowledge that you understand these risks and agree to conduct your own research before making any investment decisions.
"""

private let termsContent = """
TERMS OF SERVICE

1. ACCEPTANCE OF TERMS

By accessing and using Ticker ("the App"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.

2. DESCRIPTION OF SERVICE

Ticker is an educational platform that provides AI-generated investment education content, including information about stocks and business ideas. The App is designed for educational purposes only.

3. USER ACCOUNTS

You must create an account to use certain features of the App. You are responsible for:
- Maintaining the confidentiality of your account credentials
- All activities that occur under your account
- Notifying us immediately of any unauthorized use

4. SUBSCRIPTION TERMS

4.1 Free Tier
Free users receive up to 10 card swipes per day.

4.2 Pro Subscription
- Pro subscribers receive 50 swipes per day
- Subscription costs $4.99/month (USD)
- Auto-renews monthly unless cancelled
- 7-day free trial (if offered)
- Cancel anytime through App Store settings

4.3 Billing
All billing is handled through Apple's App Store. Refunds are subject to Apple's refund policy.

5. USER CONDUCT

You agree not to:
- Use the App for any illegal purpose
- Attempt to gain unauthorized access to the App or its systems
- Interfere with or disrupt the App's functionality
- Use the App to make actual investment decisions without consulting a licensed financial advisor
- Scrape, data mine, or extract data from the App

6. INTELLECTUAL PROPERTY

All content, trademarks, and data in the App are owned by Ticker or its licensors. You may not copy, distribute, or create derivative works without permission.

7. DISCLAIMERS

THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION PROVIDED.

8. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY LAW, TICKER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP.

9. TERMINATION

We reserve the right to terminate or suspend your account at any time for violation of these terms.

10. CHANGES TO TERMS

We may modify these terms at any time. Continued use of the App after changes constitutes acceptance of the new terms.

11. GOVERNING LAW

These terms are governed by the laws of [Your State/Country].

12. CONTACT

For questions about these terms, contact: support@tickerapp.com
"""

private let privacyContent = """
PRIVACY POLICY

Last Updated: \(Date().formatted(date: .long, time: .omitted))

1. INFORMATION WE COLLECT

1.1 Account Information
- Email address
- Authentication credentials (managed by Firebase Auth)
- User profile (investment preferences, risk tolerance, interests)

1.2 Usage Information
- Card swipes and interactions
- Saved investments
- App analytics (screens visited, features used)
- Device information (model, OS version)

1.3 Information from Third Parties
- Authentication data (Apple Sign-In)
- Payment information (processed by Apple, not stored by us)

2. HOW WE USE YOUR INFORMATION

We use your information to:
- Provide and improve the App's functionality
- Personalize investment recommendations
- Process subscriptions
- Send notifications (with your permission)
- Analyze usage patterns
- Ensure security and prevent fraud

3. HOW WE SHARE YOUR INFORMATION

We DO NOT sell your personal information.

We may share information with:
- Firebase/Google Cloud (hosting and database)
- RevenueCat (subscription management)
- OpenAI (to generate personalized recommendations - anonymized)
- Analytics providers (Firebase Analytics)

All third-party services are bound by confidentiality obligations.

4. DATA SECURITY

We implement industry-standard security measures including:
- Encryption in transit (HTTPS/TLS)
- Firebase Security Rules
- Secure authentication
- Regular security audits

However, no system is 100% secure. Use the App at your own risk.

5. YOUR RIGHTS

You have the right to:
- Access your data
- Correct inaccurate data
- Delete your account and data
- Opt out of notifications
- Export your saved investments

To exercise these rights, contact: support@tickerapp.com

6. DATA RETENTION

We retain your data:
- While your account is active
- For 30 days after account deletion (for backup/recovery)
- Analytics data may be retained longer in anonymized form

7. CHILDREN'S PRIVACY

Ticker is not intended for users under 18. We do not knowingly collect information from children.

8. CALIFORNIA PRIVACY RIGHTS

California residents have additional rights under CCPA. Contact us to exercise these rights.

9. INTERNATIONAL USERS

Your data may be transferred to and processed in the United States or other countries where our service providers operate.

10. CHANGES TO PRIVACY POLICY

We will notify you of material changes to this policy via email or in-app notification.

11. CONTACT US

For privacy questions: privacy@tickerapp.com
"""



